version: '2'
services:
  app:
    container_name: chonk-mongo
    restart: on-failure
    build: .
    ports:
      - '80:1337'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'